# Site Settings
lang: ja                            # 言語を日本語に設定(デフォルトでは"en")
favicon: /assets/img/favicon.png    # faviconを設定
timezone: Asia/Tokyo                # タイムゾーンを東京に設定

# リモートテーマを設定
remote_theme: chrisrhymes/bulma-clean-theme

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from
  - jekyll-remote-theme   # リモートテーマプラグイン追加
  - jemoji                # 絵文字プラグイン追加

title: same log
description: There are Sharks Underwater!!
url: https://mizusameblue.github.io
baseurl: /blog
permalink: /:year/:month/:title:output_ext
excerpt_separator: "<!--more-->"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"

#pager
plugins:
  - jekyll-paginate

paginate: 10
paginate_path: "page/:num"
