remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: same log
description: Slate is a theme for GitHub Pages.

permalink: /:year/:month/:title:output_ext
