theme: jekyll-theme-cayman
title: same log
description: [A short description of your site's purpose]

defaults:
- scope:
    path: ""
    type: "posts"
  values:
    permalink: /:year/:month/:title.html
