title: same log
description: Slate is a theme for GitHub Pages.
url: https://mizusameblue.github.io
baseurl: /blog

permalink: /:year/:month/:title:output_ext

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
