theme: jekyll-theme-cayman
title: same log
description: [A short description of your site's purpose]
url: https://mizusameblue.github.io
baseurl: /blog

collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:title
